# Generated by Django 5.2.4 on 2025-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldrequest',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='requester_email',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='requester_name',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='requester_phone',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fieldrequest',
            name='unit',
        ),
        migrations.AddField(
            model_name='fieldrequest',
            name='caretaker',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fieldrequest',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
