# Generated by Django 5.2.4 on 2025-08-17 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_mgmt', '0002_remove_fieldrequest_actual_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMgmtTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'field_mgmt_technical',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldMgmtTechnicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('mime_type', models.CharField(default='image/png', max_length=50)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('technical_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='field_mgmt.fieldmgmttechnical')),
            ],
            options={
                'db_table': 'field_mgmt_fieldmgmttechnicalimage',
            },
        ),
    ]
