# Generated by Django 5.2.4 on 2025-08-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_mgmt', '0003_fieldmgmttechnical_fieldmgmttechnicalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmgmttechnical',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
