# Generated by Django 5.2.4 on 2025-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_mgmt', '0004_alter_fieldmgmttechnical_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmgmttechnical',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
