# Generated by Django 5.2.4 on 2025-09-13 16:13

from django.db import migrations
import string
import random


def generate_unique_codes(apps, schema_editor):
    """Populate existing records with unique codes"""
    FieldMgmtTechnical = apps.get_model('field_mgmt', 'FieldMgmtTechnical')

    existing_codes = set()
    characters = string.ascii_uppercase + string.digits

    for technical_request in FieldMgmtTechnical.objects.filter(code__isnull=True):
        while True:
            code = ''.join(random.choices(characters, k=8))
            if code not in existing_codes:
                existing_codes.add(code)
                technical_request.code = code
                technical_request.save()
                break


def reverse_generate_unique_codes(apps, schema_editor):
    """Reverse migration - set codes to null"""
    FieldMgmtTechnical = apps.get_model('field_mgmt', 'FieldMgmtTechnical')
    FieldMgmtTechnical.objects.update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('field_mgmt', '0005_fieldmgmttechnical_code'),
    ]

    operations = [
        migrations.RunPython(
            generate_unique_codes,
            reverse_generate_unique_codes
        ),
    ]
