# Generated by Django 5.2.4 on 2025-09-13 16:14

import field_mgmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_mgmt', '0006_auto_20250913_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmgmttechnical',
            name='code',
            field=models.CharField(default=field_mgmt.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
