# Generated by Django 5.2.4 on 2025-08-18 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('meetingEvent', 'Meeting Event'), ('generalEvent', 'General Event'), ('maintenanceEvent', 'Maintenance Event'), ('emergencyEvent', 'Emergency Event')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('condominium', models.CharField(max_length=255)),
                ('people_involved', models.JSONField(default=list)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts_mgmt_event',
                'ordering': ['-date_time'],
            },
        ),
    ]
