# Generated by Django 5.2.4 on 2025-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsevent',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
    ]
