# Generated by Django 5.2.4 on 2025-08-18 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_mgmt', '0002_alter_contactsevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('condominium', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('phone_numbers', models.JSONField(default=list)),
                ('service_category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts_mgmt_supplier',
                'ordering': ['-created_at'],
            },
        ),
    ]
