# Generated by Django 5.2.4 on 2025-08-01 13:03

import auth_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, spaces and @/./+/-/_ only.', max_length=150, unique=True, validators=[auth_system.models.CustomUsernameValidator()]),
        ),
    ]
