# Generated by Django 5.2.4 on 2025-08-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_alter_user_username'),
        ('building_mgmt', '0005_alter_building_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='building_mgmt.building'),
        ),
    ]
