# Generated by Django 5.2.4 on 2025-09-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_docs', '0002_legaltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaltemplate',
            name='building_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='legaltemplate',
            name='due_month',
            field=models.CharField(blank=True, choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='legaltemplate',
            name='responsible_emails',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses'),
        ),
        migrations.AlterField(
            model_name='legaltemplate',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One Time'), ('annual', 'Annual'), ('biannual', 'Biannual'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual')], default='annual', max_length=20),
        ),
    ]
