# Generated by Django 5.2.4 on 2025-09-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_docs', '0003_legaltemplate_building_type_legaltemplate_due_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaltemplate',
            name='building_types',
        ),
        migrations.RemoveField(
            model_name='legaltemplate',
            name='days_before_expiry',
        ),
    ]
