# Generated by Django 5.2.4 on 2025-09-15 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0006_replace_block_with_building'),
        ('legal_docs', '0004_remove_legaltemplate_building_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaltemplate',
            name='building_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building_mgmt.building'),
        ),
        migrations.AddField(
            model_name='legaltemplate',
            name='notice_period',
            field=models.IntegerField(default=14, help_text='Notice period in days'),
        ),
        migrations.AlterField(
            model_name='legaltemplate',
            name='due_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
