# Generated by Django 5.2.4 on 2025-09-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_docs', '0005_legaltemplate_building_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaltemplate',
            old_name='building_id',
            new_name='building',
        ),
    ]
