# Generated by Django 5.2.4 on 2025-09-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_docs', '0006_rename_building_id_legaltemplate_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaltemplate',
            name='frequency',
            field=models.CharField(default='annual', max_length=50),
        ),
    ]
