# Generated by Django 5.2.4 on 2025-08-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0005_alter_building_created_by'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMainAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('main', 'Main Account'), ('sub', 'Sub Account'), ('detailed', 'Detailed Account')], max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='building_mgmt.building')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='financials.financialmainaccount')),
            ],
            options={
                'db_table': 'financials_main_account',
                'unique_together': {('building', 'code')},
            },
        ),
    ]
