# Generated by Django for equipment structure update

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_mgmt', '0001_initial'),
    ]

    operations = [
        # Add new required fields
        migrations.AddField(
            model_name='equipment',
            name='condominium',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_frequency',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('weekly', 'Weekly'),
                    ('monthly', 'Monthly'),
                    ('quarterly', 'Quarterly'),
                    ('semi_annual', 'Semi-Annual'),
                    ('annual', 'Annual'),
                ],
                default='monthly',
            ),
        ),
        migrations.AddField(
            model_name='equipment',
            name='contractor_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='contractor_phone',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        # Modify existing fields to be optional
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name='equipment',
                to='building_mgmt.building'
            ),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('elevator', 'Elevator'),
                    ('generator', 'Generator'),
                    ('pump', 'Water Pump'),
                    ('hvac', 'HVAC System'),
                    ('fire_system', 'Fire Safety System'),
                    ('security_system', 'Security System'),
                    ('garage_door', 'Garage Door'),
                    ('intercom', 'Intercom System'),
                    ('lighting', 'Lighting System'),
                    ('other', 'Other Equipment'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        # Remove the old maintenance_frequency_months field dependency for now
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance_frequency_months',
        ),
    ]