# Generated by Django 5.2.4 on 2025-08-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_mgmt', '0003_fix_installation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='warranty_expiry',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='building',
        ),
    ]
