# Generated by Django 5.2.4 on 2025-08-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_mgmt', '0004_auto_20250811_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='notes',
        ),
    ]
