# Generated by Django 5.2.4 on 2025-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_mgmt', '0006_update_maintenance_record_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='maintenance_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-Annual'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
