# Generated by Django 5.2.4 on 2025-07-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('building_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use')], default='residential', max_length=20)),
                ('total_units', models.PositiveIntegerField()),
                ('floors', models.PositiveIntegerField()),
                ('year_built', models.PositiveIntegerField()),
                ('total_area_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('common_area_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_phone', models.CharField(max_length=20)),
                ('manager_email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('municipal_registration', models.CharField(blank=True, max_length=50)),
                ('monthly_common_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserve_fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('store', 'Store'), ('parking', 'Parking Space'), ('storage', 'Storage')], default='apartment', max_length=20)),
                ('floor', models.PositiveIntegerField()),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_cpf', models.CharField(max_length=14)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('common_fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='building_mgmt.building')),
            ],
            options={
                'unique_together': {('building', 'unit_number')},
            },
        ),
    ]
