# Generated by Django 5.2.4 on 2025-08-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0001_initial'),
    ]

    operations = [
        # Create Address model
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
            ],
        ),
        
        # Remove old fields from Building
        migrations.RemoveField(model_name='building', name='address'),
        migrations.RemoveField(model_name='building', name='floors'),
        migrations.RemoveField(model_name='building', name='total_units'),
        migrations.RemoveField(model_name='building', name='year_built'),
        migrations.RemoveField(model_name='building', name='total_area_sqm'),
        migrations.RemoveField(model_name='building', name='common_area_sqm'),
        migrations.RemoveField(model_name='building', name='manager_email'),
        migrations.RemoveField(model_name='building', name='registration_number'),
        migrations.RemoveField(model_name='building', name='municipal_registration'),
        migrations.RemoveField(model_name='building', name='monthly_common_fee'),
        migrations.RemoveField(model_name='building', name='reserve_fund_balance'),
        
        # Rename name to building_name
        migrations.RenameField(model_name='building', old_name='name', new_name='building_name'),
        
        # Alter manager_phone field to allow longer phones
        migrations.AlterField(
            model_name='building',
            name='manager_phone',
            field=models.CharField(max_length=30),
        ),
        
        # Add new fields to Building
        migrations.AddField(
            model_name='building',
            name='manager_phone_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('landline', 'Landline')], default='mobile', max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='use_separate_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='number_of_towers',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='apartments_per_tower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='residential_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='commercial_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='non_residential_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='studio_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='wave_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        
        # Add address foreign keys
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_primary', to='building_mgmt.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='alternative_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_alternative', to='building_mgmt.address'),
        ),
        
        # Create Tower model
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units_per_tower', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='building_mgmt.building')),
            ],
        ),
        
        # Create TowerUnitDistribution model
        migrations.CreateModel(
            name='TowerUnitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial', models.PositiveIntegerField(default=0)),
                ('non_residential', models.PositiveIntegerField(default=0)),
                ('residential', models.PositiveIntegerField(default=0)),
                ('studio', models.PositiveIntegerField(default=0)),
                ('wave', models.PositiveIntegerField(default=0)),
                ('tower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_distribution', to='building_mgmt.tower')),
            ],
        ),
    ]
