# Generated by Django 5.2.4 on 2025-08-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0003_auto_update_unit_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='building_mgmt.tower'),
        ),
    ]
