# Generated by Django 5.2.4 on 2025-09-09 09:49

from django.db import migrations, models
import django.db.models.deletion


def forward_migration(apps, schema_editor):
    Unit = apps.get_model('building_mgmt', 'Unit')
    Tower = apps.get_model('building_mgmt', 'Tower')
    
    # Copy data from block (Tower) to building for all units
    for unit in Unit.objects.all():
        if unit.block:  # block is the Tower (old field)
            unit.building = unit.block.building
            unit.save()


def reverse_migration(apps, schema_editor):
    # This would be complex to reverse since we'd need to recreate tower associations
    # For now, we'll raise an error to prevent accidental reversal
    raise RuntimeError("Cannot reverse this migration - data would be lost")


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0005_alter_building_created_by'),
    ]

    operations = [
        # Step 1: Add the new building field (nullable for now)
        migrations.AddField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='building_mgmt.building'),
        ),
        
        # Step 2: Copy data from block to building
        migrations.RunPython(forward_migration, reverse_migration),
        
        # Step 3: Make building field non-nullable
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='building_mgmt.building'),
        ),
        
        # Step 4: Remove the old block field
        migrations.RemoveField(
            model_name='unit',
            name='block',
        ),
    ]
