# Generated by Django 5.2.4 on 2025-09-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0010_make_has_deposit_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='has_deposit',
        ),
    ]
